language: go
go:
- '1.13'
- '1.14'
- '1.15'
arch:
  - amd64
  - arm64
env:
  - DOCKER_PREFIX=ottenwbe/

install:
  - go get -u golang.org/x/lint/golint

script:
  - make build
  - go get -u github.com/onsi/ginkgo/ginkgo
  - go get -u github.com/onsi/gomega/...
  - make verify
  - make release
  - make docker  

deploy:
  provider: script
  script: make docker-push
 