language: go
go:
- '1.16'
arch:
  - amd64

dist: focal
addons:
  apt:
    sources:
      - sourceline: 'deb https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable'

env:
  global:
    - GO_COOK_DOCKER_PREFIX=ottenwbe/ GOFLAGS=-mod=vendor

services:
  - docker

before_install:
  - sudo rm -rf /var/lib/apt/lists/*
  - sudo apt-get update
  - mkdir -vp ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.3.0.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
  - sudo apt-get install -y qemu-user-static binfmt-support
  - docker buildx create --use

install:
  - GO111MODULE=off go get -u golang.org/x/lint/golint
  - GO111MODULE=off go get -u github.com/onsi/ginkgo/ginkgo
  - GO111MODULE=off go get -u github.com/onsi/gomega/...
  - GO111MODULE=off go get -u github.com/swaggo/swag/cmd/swag

script:
  - make verify # qa steps
  - make api-docu
  - make release
  - make docker

deploy:
  provider: script
  script: make docker-buildx
  on:
    tags: true