language: go
go:
- '1.15'
arch:
  - amd64

dist: focal
addons:
  apt:
    sources:
      - sourceline: 'deb https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable'

env:
  global:
    - GO_COOK_DOCKER_PREFIX=ottenwbe/

before_install:
  - sudo rm -rf /var/lib/apt/lists/*
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce docker-ce-cli containerd.io
  - sudo apt-get install -y qemu-user-static binfmt-support
  - docker buildx create --use

install:
  - go get -u golang.org/x/lint/golint
  - go get -u github.com/onsi/ginkgo/ginkgo
  - go get -u github.com/onsi/gomega/...
  - go get -u github.com/swaggo/swag/cmd/swag
  -
script:
  - make verify # qa steps
  - make api-docu
  - make release
  - make docker

deploy:
  provider: script
  script: make docker-buildx
  on:
    all_branches: true
    #tags: true